[package]
name = "ifshow"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
pnet = "0.35.0"
log = "0.4.28"

[lib]
path = "lib.rs"

[[bin]]
name = "ifshow"
path = "main.rs"
bench = false
